### ISSUE TITLE
Form Builder 的reset 无效，建议两个按钮左对齐，不要间隔太大，表单也可以选择是左对齐还是右对齐。如果查询表单为空，建议展示所有值，而不是显示空表格

### ISSUE THREAD

**Issue by skywalkerhw** [jsding/dbface-issues#24]
![qq 20170125135922](https://cloud.githubusercontent.com/assets/13765913/22279588/852df2e2-e306-11e6-8bb5-028d56510491.png)

**Comment by jsding** [comment]
reset按钮将字段值设置为默认值，无效是因为没有设置项目的默认值. 查询表单为空的行为取决于脚本，用户可以在为空时，再脚本中删除其条件
